# Generated by Django 5.2.7 on 2025-10-04 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid_config', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='measurements/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('main_band', models.CharField(blank=True, db_index=True, max_length=50)),
                ('ca_label', models.CharField(blank=True, db_index=True, max_length=100)),
                ('port_label', models.CharField(blank=True, db_index=True, max_length=100)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('is_parsed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='rf_analyzer.measurementsession')),
            ],
            options={
                'ordering': ['main_band', 'ca_label', 'port_label'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfg_band', models.CharField(db_index=True, max_length=20)),
                ('cfg_lna_gain_state', models.CharField(db_index=True, max_length=10)),
                ('cfg_active_port_1', models.CharField(db_index=True, max_length=10)),
                ('cfg_active_port_2', models.CharField(max_length=10)),
                ('debug_nplexer_bank', models.CharField(db_index=True, max_length=100)),
                ('active_rf_path', models.CharField(db_index=True, max_length=10)),
                ('frequency_mhz', models.FloatField(db_index=True)),
                ('gain_db', models.FloatField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='rf_analyzer.measurementsession')),
            ],
            options={
                'ordering': ['cfg_band', 'cfg_lna_gain_state', 'cfg_active_port_1', 'frequency_mhz'],
                'indexes': [models.Index(fields=['cfg_band', 'cfg_lna_gain_state', 'cfg_active_port_1'], name='rf_analyzer_cfg_ban_9fded4_idx'), models.Index(fields=['cfg_band', 'debug_nplexer_bank'], name='rf_analyzer_cfg_ban_1d24f3_idx'), models.Index(fields=['active_rf_path', 'frequency_mhz'], name='rf_analyzer_active__dcb15a_idx')],
            },
        ),
    ]
