# Generated by Django 5.2.7 on 2025-10-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementfile',
            name='file_type',
            field=models.CharField(choices=[('snp', 'SnP File'), ('csv', 'CSV File')], default='csv', max_length=10),
        ),
    ]
